# Скопируйте в secret.yaml и заполните значения в base64
# Никогда не коммитьте секреты в репозиторий!

apiVersion: v1
kind: Secret
metadata:
  name: emitter-secrets
type: Opaque
data:
  # openssl rand -base64 32
  VMA_SIGNING_KEY: <base64_encoded_private_key>
  CANONICAL_SIGNER_ID: <base64_encoded_signer_id>