apiVersion: v1
kind: Service
metadata:
  name: onto-emitter-service
spec:
  selector:
    app: onto-emitter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP